services:
  - type: web
    name: auth-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://semestercse12:IBL5DCsFz9Rk20Ze@cluster0.2nj6ddw.mongodb.net/
      - key: JWT_SECRET
        value: 47ef6b6ef0ae37bd4740d941aa63fd3e81d1665f32c2333fd72dadb103fde5495a1ed8358ce27d78a0087bde41013077f864eee3b6df4ddf3c2e426ce67ce4ea
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production

  - type: static
    name: auth-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://auth-backend.onrender.com
