services:
  - type: web
    name: auth-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGO_URI
        value: your_mongodb_atlas_connection_string
      - key: JWT_SECRET
        value: your_strong_jwt_secret
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production

  - type: static
    name: auth-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://auth-backend.onrender.com